package com.babynode.automotive

import kotlinx.coroutines.flow.Flow

/**
 * Canonical command sent from BabyNode Automotive to BabyNodeCAN.
 *
 * Android remains CAN-agnostic. Vehicle-specific CAN identifiers,
 * payloads, validation, and transmission belong exclusively in
 * BabyNodeCAN.
 */
data class CanonicalCommand(
    val command: String,
    val value: String? = null
)

/**
 * Identifies a command request accepted by the transport.
 *
 * The request ID is generated by the transport and carried through
 * sent, response, timeout, and failure events.
 */
data class CarCommandRequest(
    val requestId: Long,
    val command: CanonicalCommand
)

/**
 * Abstraction over the BabyNode Automotive transport layer.
 *
 * Implementations must explicitly provide every transport operation.
 * No default no-op behavior is allowed.
 */
interface CarCanTransport {

    /**
     * Connects to the underlying transport.
     */
    suspend fun connect()

    /**
     * Disconnects from the underlying transport.
     *
     * Unlike close(), disconnect() may leave the implementation
     * available for a deliberate future reconnection.
     */
    suspend fun disconnect()

    /**
     * Submits one canonical command.
     *
     * Returns the transport-generated request identity after the
     * command has been successfully written to the transport.
     *
     * Returning the request identity lets the originating voice,
     * typed, or configuration path follow only its own events.
     *
     * Throws when the command cannot be written. The transport also
     * emits a request-correlated Error event when a request identity
     * was allocated before the failure.
     */
    suspend fun sendCommand(
        command: CanonicalCommand
    ): CarCommandRequest

    /**
     * Exposes connection, request, response, and error events.
     */
    fun status():
        Flow<CarStatusEvent>

    /**
     * Permanently releases transport resources.
     *
     * A transport must not be reused after close().
     */
    fun close()
}

/**
 * Events emitted by a CarCanTransport implementation.
 *
 * These classes intentionally contain no Android framework calls,
 * logging side effects, or transport behavior. They remain pure data
 * objects that can be used in ordinary JVM unit tests.
 */
sealed interface CarStatusEvent {

    /**
     * The transport established a usable connection.
     */
    data class Connected(
        val transportName: String
    ) : CarStatusEvent

    /**
     * The transport connection closed.
     */
    data class Disconnected(
        val transportName: String
    ) : CarStatusEvent

    /**
     * A transport-level or request-level failure.
     *
     * requestId and command are null for failures that do not belong
     * to one specific command, such as connection startup failures.
     */
    data class Error(
        val message: String,
        val throwable: Throwable? = null,
        val requestId: Long? = null,
        val command: CanonicalCommand? = null
    ) : CarStatusEvent {

        val isRequestSpecific:
            Boolean
            get() =
                requestId != null &&
                    command != null
    }

    /**
     * A canonical command was successfully written to the active
     * transport.
     *
     * This event means the request was transmitted. It does not mean
     * BabyNodeCAN accepted it or that a physical vehicle action
     * occurred.
     */
    data class CommandSent(
        val requestId: Long,
        val command: CanonicalCommand
    ) : CarStatusEvent

    /**
     * BabyNodeCAN returned a validated response whose request ID and
     * command matched an outstanding request.
     *
     * An "ok" response means BabyNodeCAN accepted the request under
     * the shared protocol. It does not by itself prove that a physical
     * vehicle action completed.
     */
    data class CommandResponse(
        val requestId: Long,
        val command: CanonicalCommand,
        val status: String
    ) : CarStatusEvent {

        /**
         * Compatibility alias for existing diagnostic UI code that
         * still refers to commandId.
         */
        val commandId:
            Long
            get() =
                requestId
    }
}